name: build-alpine-images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * 0"
  push:
    branches: 
      - main
    paths:
      - "alpine/**"
      - ".github/workflows/alpine.yaml"
      - ".ci/alpine.sh"


jobs:
  images-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_NAME }}
          password: ${{ secrets.CR_PAT }}
      - name: Set Env
        run: echo "TIMESTAMP=$(date +%y.%m.%d.%H.%M)" >> $GITHUB_ENV
      - name: Docker build & push
        env:
          PROJECT_VERSION: 1.0.0
          TAG_VERSION: ${{ github.run_number }}
          PROJECT_DIR: ${{ github.workspace }}
          CI_REGISTRY: ghcr.io
          PLATFORM: linux/386,linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
        run: |
          sudo apt update && sudo apt install curl jq &&
          chmod +x .ci/alpine.sh &&
          .ci/alpine.sh
