name: activity

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 15 10 * *"

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - uses: fregante/setup-git-user@v2
      - name: activity
        run: |
          TIMESTAMP=$(date +%y%m%d%H%M)
          echo "${TIMESTAMP}" >> .github/auto-activity
          git add .
          git commit -m "activity ${TIMESTAMP}"
          git push
