name: build-oraclelinux-images

on:
  workflow_dispatch:
  schedule:
    - cron: "20 19 * * 0"
  push:
    branches: 
      - main
    paths:
      - "oraclelinux/**"
      - ".github/workflows/oraclelinux.yaml"
      - "build-bin/oraclelinux.sh"


jobs:
  images-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_NAME }}
          password: ${{ secrets.CR_PAT }}
      - name: Set Env
        run: echo "TIMESTAMP=$(date +%y.%m.%d.%H.%M)" >> $GITHUB_ENV
      - name: Docker build & push
        env:
          PROJECT_VERSION: 1.0.0
          TAG_VERSION: ${{ github.run_number }}
          CI_REGISTRY: ghcr.io
          PROJECT_DIR: ${{ github.workspace }}
          PLATFORM: linux/amd64,linux/arm64/v8
        run: |
          sudo apt update && sudo apt install curl jq &&
          chmod +x build-bin/oraclelinux.sh &&
          build-bin/oraclelinux.sh
