name: build-oraclelinux-images

on:
  workflow_dispatch:
  schedule:
    - cron: "20 19 * * 0"
  push:
    branches: 
      - main
    paths:
      - "oraclelinux/**"
      - ".github/workflows/oraclelinux.yaml"
      - "build-bin/oraclelinux.sh"


jobs:
  images-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Env
        run: echo "TIMESTAMP=$(date +%y.%m.%d.%H.%M)" >> $GITHUB_ENV
      - name: Docker build & push
        env:
          PROJECT_VERSION: 1.0.0
          TAG_VERSION: ${{ github.run_number }}
          CI_DEPLOY_USER: ${{ secrets.CR_NAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CR_PAT }}
          CI_REGISTRY: ghcr.io
          PROJECT_DIR: ${{ github.workspace }}
        run: |
          sudo apt update && sudo apt install curl &&
          echo ${CI_DEPLOY_PASSWORD} | docker login ${CI_REGISTRY} -u ${CI_DEPLOY_USER} --password-stdin &&
          chmod +x build-bin/oraclelinux.sh &&
          build-bin/oraclelinux.sh
